CREATE TABLE Society (
	SID	ID_No	PRIMARY KEY,
	Community	VARCHAR(35) NOT NULL
);


CREATE TABLE AMemberShip (
	DID	ID_NO	PRIMARY KEY,
	AID	ID_NO,
	SID	ID_NO,
	Description	VARCHAR(35)
);

ALTER TABLE AMemberShip
	ADD CONSTRAINT	fkAlumniMemberShip	FOREIGN KEY	(AID)	REFERENCES	Alumni	(AID)	ON DELETE CASCADE ON UPDATE CASCADE,
	ADD CONSTRAINT	fkSocietyMemberShip	FOREIGN KEY	(SID)	REFERENCES	Society	(SID)	ON DELETE CASCADE ON UPDATE CASCADE
;


INSERT INTO Society (SID, Community) VALUES (1, 'BPH Iluni Teknik');
INSERT INTO Society (SID, Community) VALUES (2, 'Koperasi Iluni Teknik');